### ISSUE TITLE
Spamnet MWM lowered to 7

### ISSUE THREAD

**Issue by geminoz** [iotaledger/documentation-markdown#35]
As part of a revamp process of the spamnet network, its MWM has been lowered to 7.

The documentation should reflect such change. Thank you

**Comment by JakeSCahill** [comment]
Thanks @geminoz . I'm on it. Will be updated on Monday along with some other changes.

**Comment by JakeSCahill** [comment]
Fixed: https://github.com/iotaledger/documentation-markdown/commit/01bc4287c1677e732cbde6cd101c5a5b952a7c55#diff-3f92e4b8f4c83dea57d3071c04d2212f
